# Generated by Django 2.0.8 on 2018-09-01 20:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('testt', '0002_auto_20180901_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publications', models.ManyToManyField(blank=True, null=True, to='testt.Publication')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='testt.Country'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testt.Publication'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='publication', chained_model_field='publications', horizontal=True, to='testt.Writer', verbose_name='writer'),
        ),
    ]
