# Generated by Django 2.0.8 on 2018-09-01 20:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('testt', '0003_auto_20180901_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testt.Continent')),
                ('country', smart_selects.db_fields.GroupedForeignKey(group_field='continent', on_delete=django.db.models.deletion.CASCADE, to='testt.Country')),
            ],
        ),
    ]
